### ISSUE TITLE
refactor: update angular versions to master builds

### ISSUE THREAD

**Issue by manekinekko** [sfeir-open-source/angular-search-experience#11]
We should use angular#master^HEAD 
See this PR as a reference: https://github.com/xlayers/xlayers/pull/50

**Comment by tinesoft** [comment]
Ok, i'm on it!

**Comment by tinesoft** [comment]
Ok, quick update on this issue:
Versions have been updated(see https://github.com/tinesoft/angular-search-experience/commit/8e86d102246d0a44de6274fff7bc02053181309f), but there are currently 2 issues when `ng building` or `ng serving` the app:
![image](https://user-images.githubusercontent.com/4053092/47065744-5abec300-d1e4-11e8-8e53-216a67eda179.png)

* first one is tracked here https://github.com/dialogflow/dialogflow-javascript-client/issues/99
* the second is related to TypesCript (🎃 ) not being happy with the use of `window`: this one i could probably fix by giving or declaring the proper typings...

**Comment by manekinekko** [comment]
thanks for the updates.

**Comment by thanhpd** [comment]
May I ask why should we switch to master builds? There's no guarantee that the latest version will work without error, which is the reason official stable releases exist.

**Comment by manekinekko** [comment]
Closing this feature request.
Reason: Angular master builds may introduce some incompatibilities with 3rd party libs.
