### ISSUE TITLE
Categories get rearranged when selected/unselected

### ISSUE THREAD

**Issue by sulco** [sfeir-open-source/angular-search-experience#3]
Since categories seems to be always ordered by selected -> unselected, when a category is clicked, it jumps into other position. 
![searchapp-store](https://user-images.githubusercontent.com/1511906/43641550-6ddad4a6-9724-11e8-9b1a-14ace4f4abba.gif)

In other applications of similar interface tags use to stay in place so the current behaviour might be confusing for users.

**Comment by manekinekko** [comment]
fixed.
